<?php

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\OTPController;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\SignInController;
use App\Http\Controllers\SignUpController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\AddressController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\admin\UserAdController;
use App\Http\Controllers\admin\BrandAdController;
use App\Http\Controllers\admin\SettingController;
use App\Http\Controllers\admin\ReportAdController;
use App\Http\Controllers\admin\SigninAdController;
use App\Http\Controllers\admin\TicketAdController;
use App\Http\Controllers\admin\ProductAdController;
use App\Http\Controllers\admin\CustomerAdController;
use App\Http\Controllers\admin\DashboardAdController;
use App\Http\Controllers\admin\ExtraController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// Route::get('/set/language/{locale}',function($locale){
//     App::setLocale($locale);
//     Session::put('lang', $locale);
//     return true;
// });
// Route::get('/',function(){
//     if(Auth::check()){
//         if(Auth::user()->type=="user"){
//             return redirect()->route('dashboard');
//         }else{
//             return redirect()->route('admin.dashboard');
//         }
//     }else{
//         return redirect('/login');
//     }
// });
// Route::post('/get/image/js',function(Request $request){
//     return str_replace('public','https://storage.googleapis.com/warranty-bill/public',$request->name);
// });
// Route::prefix('signin')->group(function(){
//     Route::get('/upload/data',[SignInController::class,'UploadData'])->name('signin.upload.data');
//     Route::get('/phone',[SignInController::class,'Phone'])->name('signin.phone');
//     Route::post('/signin',[SignInController::class,'Signin'])->name('signin.signin');
//     Route::get('/forget-password',[SignInController::class,'ForgetPassword'])->name('signin.forget.password');
//     Route::get('/check/exist/{phone}',[SignInController::class,'CheckExist'])->name('signin.check.exist');
//     Route::get('/check/all/exist/{phone}',[SignInController::class,'CheckAllExist'])->name('signin.check.all.exist');
//     Route::get('/send/email/{id}',[SignInController::class,'EmailSend'])->name('signin.email.send');
// });
// Route::get('/reset-password',[SignInController::class,'ResetPassword'])->name('reset.password');
// Route::post('/check/old/password',[SignInController::class,'CheckOld'])->name('reset.check.old');
// Route::post('/reset-password/data/{id}',[SignInController::class,'ResetData'])->name('reset.data');
// Route::prefix('signup')->group(function(){
//     Route::get('/',[SignUpController::class,'Index'])->name('signup');
//     Route::post('/data',[SignUpController::class,'Signup'])->name('signup.signup');
//     Route::get('/check/phone/{phone}',[SignUpController::class,'Checkphone'])->name('signup.check.phone');
//     Route::get('/check/phone/edit/{phone}/{id}',[SignUpController::class,'CheckphoneEdit'])->name('signup.check.phone.edit');
//     Route::middleware('permission')->get('/info',[SignUpController::class,'Info'])->name('signup.info');
//     Route::middleware('permission')->get('/google/info/{givingName}/{familyName}',[SignUpController::class,'InfoGoogle'])->name('signup.google.info');
//     Route::middleware('permission')->get('/term',[SignUpController::class,'Term'])->name('signup.term');
//     Route::middleware('permission')->post('/declined',[SignUpController::class,'Declined'])->name('signup.declined');
//     Route::middleware('permission')->post('/accept',[SignUpController::class,'Accept'])->name('signup.accept');
//     Route::middleware('permission')->post('/info/data',[SignUpController::class,'InfoData'])->name('signup.info.data');
// });

// Route::prefix('/address')->group(function(){
//     Route::get('/province/store',[AddressController::class,'ProvinceStore'])->name('address.province.store');
//     Route::get('/province',[AddressController::class,'Province'])->name('address.province');
//     Route::get('/district/{id}',[AddressController::class,'District'])->name('address.district');
//     Route::get('/subdistrict/{id}',[AddressController::class,'SubDistrict'])->name('address.subdistrict');
// });
// Route::middleware('permission')->prefix('/dashboard')->group(function(){
//     Route::get('/index',[DashboardController::class,'index'])->name('dashboard');
//     Route::get('/condition',[DashboardController::class,'Condition'])->name('dashboard.condition');
//     Route::get('/contact',[DashboardController::class,'Contact'])->name('dashboard.contact');
//     Route::get('/search',[DashboardController::class,'Search'])->name('dashboard.search');
//     Route::get('/add/product',[DashboardController::class,'AddProduct'])->name('dashboard.add.product');
//     Route::get('/data/show/{type}/{search?}',[DashboardController::class,'DataShow'])->name('dashboard.data.show');
//     Route::get('/search/table/{name}/{sku}',[DashboardController::class,'SearchTable'])->name('dashboard.search.table');
//     Route::get('/show/load/amount/{type}',[DashboardController::class,'ShowLoadData'])->name('dashboard.show.load');
// });
// Route::middleware('permission')->prefix('/user')->group(function(){
//     Route::post('/edit',[UserController::class,'EditProfile'])->name('user.edit');
//     Route::post('/change/password',[UserController::class,'ChangePassword'])->name('user.change.password');
// });
// Route::middleware('permission')->prefix('/brand')->group(function(){
//     Route::get('/search',[BrandController::class,'Search'])->name('brand.search');
//     Route::get('/search/sku',[BrandController::class,'SearchSKU'])->name('brand.search.sku');
// });
// Route::middleware('permission')->prefix('/product')->group(function(){
//     Route::get('/extra',[ProductController::class,'Extra'])->name('product.extra');
//     Route::get('/search',[ProductController::class,'Search'])->name('product.search');
//     Route::post('/search/sku/',[ProductController::class,'SearchSku'])->name('product.search.sku');
//     Route::get('/add/index',[ProductController::class,'AddIndex'])->name('product.add.index');
//     Route::post('/add/data',[ProductController::class,'AddData'])->name('product.add.data');
//     Route::post('/model/check',[ProductController::class,'CheckModel'])->name('product.check.model');
//     Route::post('/extra/request',[ProductController::class,'ExtraRequest'])->name('product.extra.request');
// });
// Route::middleware('permission')->prefix('ticket')->group(function(){
//     Route::get('/index/{id}',[TicketController::class,'Index'])->name('ticket.index');
//     Route::get('/get/post/{ticketId}/{last}',[TicketController::class,'GetTicketPost'])->name('ticket.get.post');
//     Route::post('/add/data/{id}',[TicketController::class,'AddData'])->name('ticket.add.data');
//     Route::post('/upload/image',[TicketController::class,'UploadImage'])->name('ticket.upload.image');
//     Route::post('/post',[TicketController::class,'Post'])->name('ticket.post');
//     Route::get('/check/status/end/{id}',[TicketController::class,'CheckStatusEnd'])->name('ticket.check.status.end');
//     Route::post('/post/current/location',[TicketController::class,'CurrentLocation'])->name('ticket.post.current');
// });
// Route::middleware('permission')->prefix('/customer')->group(function(){
//     Route::post('/create',[CustomerController::class,'Create'])->name('user.create');
//     Route::post('/generate',[CustomerController::class,'Generate'])->name('user.generate');
// });
// Route::middleware('permission')->prefix('/store')->group(function(){
//     Route::get('/search',[StoreController::class,'Search'])->name('user.store.search');
//     Route::get('/province/search',[StoreController::class,'SearchProvince'])->name('user.store.province.address');
// });

// Route::get('/auth/redirect',[GoogleController::class,'Redirect']);
// Route::get('/auth/callback',[GoogleController::class,'Callback']);
// Route::prefix('/otp')->group(function(){
//     Route::get('/login/{id}',[OTPController::class,'Login'])->name('otp.login');
//     Route::get('/check/{id}',[OTPController::class,'Check'])->name('otp.check');
//     Route::get('/resend/{userId}',[OTPController::class,'Resend'])->name('otp.resend');
// });
// Route::prefix('admin')->group(function(){
//     Route::middleware('permission.admin')->prefix('/user')->group(function(){
//         Route::get('/search',[UserController::class,'Search'])->name('admin.user.search');
//         Route::post('/edit',[UserController::class,'EditProfile'])->name('admin.user.edit');
//         Route::post('/change/password',[UserController::class,'ChangePassword'])->name('admin.user.change.password');
//     });
//     Route::middleware('permission.admin')->prefix('/brand')->group(function(){
//         Route::get('/sku/search',[BrandAdController::class,'SkuSearch'])->name('admin.search.sku');
//         Route::get('/brand/search',[BrandAdController::class,'BrandSearch'])->name('admin.search.brand');
//     });
//     Route::get('/',function(){
//         return redirect()->route('admin.signin.index');
//     })->name('admin.index');
//     Route::prefix('signin')->group(function(){
//         Route::get('/',[SigninAdController::class,'Index'])->name('admin.signin.index');
//         Route::get('/check/exist/{phone}',[SigninAdController::class,'CheckExist'])->name('admin.signin.check.exist');
//         Route::post('/signin',[SigninAdController::class,'Signin'])->name('admin.signin.signin');
//     });
//     Route::middleware('permission.admin')->prefix('dashboard')->group(function(){
//         Route::get('/index',[DashboardAdController::class,'index'])->name('admin.dashboard'); 
//         Route::get('/extra/{type}',[DashboardAdController::class,'ExtraIndex'])->name('admin.dashboard.extra');
//         Route::get('/show/data/{type}/{search}',[DashboardAdController::class,'ShowData'])->name('admin.dashboard.show.data');
//         Route::get('/chart/brand/{type}',[DashboardAdController::class,'ChartBrand'])->name('admin.dashboard.chart.brand');
//         Route::get('/chart/sku/{type}',[DashboardAdController::class,'ChartSku'])->name('admin.dashboard.chart.sku');
//         Route::get('/export/brand/{type}',[DashboardAdController::class,'ExportBrand'])->name('admin.dashboard.export.brand');
//         Route::get('/export/sku/{type}',[DashboardAdController::class,'ExportSKU'])->name('admin.dashboard.export.sku');
//         Route::get('/brand/amount/{id}',[DashboardAdController::class,'BrandAmount'])->name('admin.dashboard.brand.amount');
//     });
//     Route::middleware('permission.admin')->prefix('report')->group(function(){
//         Route::get('/index',[ReportAdController::class,'index'])->name('admin.report');
//         Route::get('/show/data/{brand}/{start}/{end}',[ReportAdController::class,'ShowData'])->name('admin.report.show.data');
//         Route::post('/show/amount/date',[ReportAdController::class,'DataDateAmount'])->name('admin.report.date.amount');
//         Route::get('/brand/{id}',[ReportAdController::class,'show'])->name('admin.report.brand');
//         Route::get('/brand/table/{id}',[ReportAdController::class,'BrandTable'])->name('admin.report.brand.table');
//         Route::get('/brand/sku/{id}',[ReportAdController::class,'sku'])->name('admin.report.brand.sku');
//         Route::get('/brand/sku/table/{id}',[ReportAdController::class,'SKUTable'])->name('admin.report.brand.sku.table');
//         Route::get('/export/brand/{id}',[ReportAdController::class,'CSVBrandModel'])->name('admin.report.export.model');
//         Route::get('/export/sku/{id}',[ReportAdController::class,'CSVProduct'])->name('admin.report.export.sku');
//         Route::post('/export/report',[ReportAdController::class,'CSVReport'])->name('admin.report.export.report');
//         Route::get('/history/{id}',[ReportAdController::class,'History'])->name('admin.report.history');
//         Route::get('/show/history/{id}',[ReportAdController::class,'HistoryTable'])->name('admin.report.history.table');
//         Route::get('/check/export/status',[ReportAdController::class,'CheckExportStatus'])->name('admin.report.check.export.status');
//         Route::get('/export/file',[ReportAdController::class,'ExportFile'])->name('admin.report.export.file');
//         Route::get('/create/export/status',[ReportAdController::class,'CreateExportStatus'])->name('admin.report.create.export.status');
//     });
//     Route::middleware('permission.admin')->prefix('product')->group(function(){
//         Route::post('/approve',[ProductAdController::class,'Approve'])->name('admin.product.approve');
//         Route::post('/super/approve',[ProductAdController::class,'SuperApprove'])->name('admin.product.super.approve');
//         Route::post('/cancel/{id}',[ProductAdController::class,'Cancel'])->name('admin.product.cancel');
//         Route::post('/cancel/super/{id}',[ProductAdController::class,'CancelSuper'])->name('admin.product.cancel.super');
//         Route::post('/add/data',[ProductAdController::class,'AddData'])->name('admin.product.add.data');
//         Route::get('/index',[ProductAdController::class,'index'])->name('admin.product');
//         Route::get('/table/{search}',[ProductAdController::class,'Table'])->name('admin.product.table');
//         Route::post('/extra/request',[ProductAdController::class,'ExtraRequest'])->name('admin.product.extra.request');
//         Route::get('/search',[ProductAdController::class,'Search'])->name('admin.product.search');
//         Route::get('/get/extra/warranty/{id}',[ProductAdController::class,'GetExtraWarranty'])->name('admin.product.get.extra.warranty');
//         Route::post('/search/sku/',[ProductAdController::class,'SearchSku'])->name('admin.product.search.sku');
//     });
//     Route::middleware('permission.admin')->prefix('ticket')->group(function(){
//         Route::get('/index',[TicketAdController::class,'index'])->name('admin.ticket');
//         Route::get('/get/post/{ticketId}/{last}',[TicketAdController::class,'GetTicketPost'])->name('admin.ticket.get.post');
//         Route::get('/table',[TicketAdController::class,'Table'])->name('admin.ticket.table');
//         Route::get('/data/{id}',[TicketAdController::class,'Data'])->name('admin.ticket.data');
//         Route::post('/upload/image',[TicketAdController::class,'UploadImage'])->name('admin.ticket.upload.image');
//         Route::post('/post',[TicketAdController::class,'Post'])->name('admin.ticket.post');
//         Route::post('/post/current/location',[TicketAdController::class,'CurrentLocation'])->name('admin.ticket.post.current');
//     });
//     Route::middleware('permission.admin')->prefix('customer')->group(function(){
//         Route::post('/customer/upload',[CustomerAdController::class,'UploadExcelChuck'])->name('admin.customer.upload.excel.chuck');
//         Route::get('/index',[CustomerAdController::class,'index'])->name('admin.customer');
//         Route::get('/product/add/{id}',[CustomerAdController::class,'ProductAdd'])->name('admin.customer.product.add');
//         Route::post('/product/add/data/{id}',[CustomerAdController::class,'ProductAddData'])->name('admin.customer.product.add.data');
//         Route::get('/table/{all}',[CustomerAdController::class,'Table'])->name('admin.customer.table');
//         Route::get('/data/{id}',[CustomerAdController::class,'Data'])->name('admin.customer.data');
//         Route::get('/data/show/{id}/{type}',[CustomerAdController::class,'DataShow'])->name('admin.customer.data.show');
//         Route::get('/search',[CustomerAdController::class,'CustomerSearch'])->name('admin.customer.search');
//         Route::post('/upload/excel',[CustomerAdController::class,'UploadExcel'])->name('admin.customer.upload.excel');
//         Route::get('/get/amount/{id}/{type}',[CustomerAdController::class,'ShowLoadData'])->name('admin.customer.show.load.amount');
//         Route::post('/csv/export',[CustomerAdController::class,'CSVCustomer'])->name('admin.customer.csv.export');
//         Route::get('/create/export/status',[CustomerAdController::class,'CreateExportStatus'])->name('admin.customer.create.export.status');
//         Route::get('/export/file',[CustomerAdController::class,'ExportFile'])->name('admin.customer.export.file');
//     });
//     Route::middleware('permission.admin')->prefix('user-management')->group(function(){
//         Route::get('/index',[UserAdController::class,'index'])->name('admin.user.management.index');
//         Route::get('/table',[UserAdController::class,'Table'])->name('admin.user.management.table');
//         Route::get('/create',[UserAdController::class,'Create'])->name('admin.user.management.create');
//         Route::post('/add/data',[UserAdController::class,'AddData'])->name('admin.user.management.add.data');
//         Route::delete('/delete/{id}',[UserAdController::class,'Delete'])->name('admin.user.management.delete');
//         Route::get('/edit/{id}',[UserAdController::class,'Edit'])->name('admin.user.management.edit');
//         Route::post('/edit/data/{id}',[UserAdController::class,'EditData'])->name('admin.user.management.edit.data');
//         Route::post('/edit/password',[UserAdController::class,'EditPassword'])->name('admin.user.management.edit.password');
//         Route::get('/phone/search',[UserAdController::class,'PhoneSearch'])->name('admin.user.management.phone.search');
//         Route::get('/generate/token/{id}',[UserAdController::class,'GenerateToken'])->name('admin.user.management.generate.token');
//     });
//     Route::middleware('permission.admin')->prefix('logout')->group(function(){
//         Route::post('/',[SigninAdController::class,'Logout'])->name('admin.logout');
//     });
//     Route::middleware('permission.admin')->prefix('setting')->group(function(){
//         Route::get('/',[SettingController::class,'Index'])->name('admin.setting.index');
//         Route::prefix('brand')->group(function(){
//             Route::get('/search',[BrandController::class,'Search'])->name('admin.setting.brand.search');
//             Route::get('/search/sku',[BrandController::class,'SearchSKU'])->name('admin.setting.brand.search.sku');
//             Route::get('/index',[SettingController::class,'BrandIndex'])->name('admin.setting.brand');
//             Route::post('/check/name',[SettingController::class,'BrandCheckName'])->name('admin.setting.brand.check.name');
//             Route::post('/check/name/edit',[SettingController::class,'BrandCheckNameEdit'])->name('admin.setting.brand.check.name.edit');
//             Route::post('/add/name',[SettingController::class,'BrandAddName'])->name('admin.setting.brand.add.name');
//             Route::post('/edit/name',[SettingController::class,'BrandEditName'])->name('admin.setting.brand.edit.name');
//             Route::get('/table',[SettingController::class,'BrandTable'])->name('admin.setting.brand.table');
//             Route::delete('/delete/{id}',[SettingController::class,'BrandDelete'])->name('admin.setting.brand.delete');
//             Route::post('/upload/excel',[SettingController::class,'UploadExcelBrand'])->name('admin.upload.excel');
//         });
//         Route::prefix('model')->group(function(){
//             Route::get('/index/{id}',[SettingController::class,'ModelIndex'])->name('admin.setting.model');
//             Route::post('/check/name/{id}',[SettingController::class,'ModelCheckName'])->name('admin.setting.model.check.name');
//             Route::post('/check/name/edit/{id}',[SettingController::class,'ModelCheckNameEdit'])->name('admin.setting.model.check.name.edit');
//             Route::post('/add/name',[SettingController::class,'ModelAddName'])->name('admin.setting.model.add.name');
//             Route::post('/edit/name',[SettingController::class,'ModelEditName'])->name('admin.setting.model.edit.name');
//             Route::get('/table/{id}',[SettingController::class,'ModelTable'])->name('admin.setting.model.table');
//             Route::delete('/delete/{id}',[SettingController::class,'ModelDelete'])->name('admin.setting.model.delete');
//             Route::post('/check/sku',[SettingController::class,'ModelCheckSKU'])->name('admin.setting.model.check.sku');
//         });
//         Route::prefix('store')->group(function(){
//             Route::get('/search',[StoreController::class,'Search'])->name('admin.setting.store.search');
//             Route::get('/index',[SettingController::class,'StoreIndex'])->name('admin.setting.store');
//             Route::post('/check/name',[SettingController::class,'StoreCheckName'])->name('admin.setting.store.check.name');
//             Route::post('/check/name/edit',[SettingController::class,'StoreCheckNameEdit'])->name('admin.setting.store.check.name.edit');
//             Route::post('/add/name',[SettingController::class,'StoreAddName'])->name('admin.setting.store.add.name');
//             Route::post('/edit/name',[SettingController::class,'StoreEditName'])->name('admin.setting.store.edit.name');
//             Route::get('/table',[SettingController::class,'StoreTable'])->name('admin.setting.store.table');
//             Route::delete('/delete/{id}',[SettingController::class,'StoreDelete'])->name('admin.setting.store.delete');
//             Route::post('/upload/excel',[SettingController::class,'UploadExcelStore'])->name('admin.store.upload.excel');
//             Route::get('/province/search',[StoreController::class,'SearchProvince'])->name('admin.store.province.address');
//         });
//         Route::prefix('product')->group(function(){
//             Route::get('/index',[SettingController::class,'ProductIndex'])->name('admin.setting.product');
//             Route::get('/add',[SettingController::class,'ProductAdd'])->name('admin.setting.product.add');
//             Route::get('/edit/{id}',[SettingController::class,'ProductEdit'])->name('admin.setting.product.edit');
//             Route::post('/check/model',[SettingController::class,'CheckModel'])->name('admin.setting.product.check.model');
//             Route::post('/add/data',[SettingController::class,'ProductAddData'])->name('admin.setting.product.add.data');
//             Route::post('/edit/data/{id}',[SettingController::class,'ProductEditData'])->name('admin.setting.product.edit.data');
//             Route::get('/table',[SettingController::class,'ProductTable'])->name('admin.setting.product.table');
//             Route::delete('/delete/{id}',[SettingController::class,'ProductDelete'])->name('admin.setting.product.delete');
//         });
//         Route::prefix('token')->group(function(){
//             Route::get('/index',[SettingController::class,'TokenIndex'])->name('admin.setting.token');
//             Route::get('/generate/token/{id}/{time}',[SettingController::class,'TokenGenerate'])->name('admin.setting.token.generate');
//         });
//     });
//     Route::middleware('permission.admin')->prefix('extra')->group(function(){
//         Route::get('/add',[ExtraController::class,'create'])->name('admin.extra.add');
//         Route::get('/edit/{id}/{type}',[ExtraController::class,'Edit'])->name('admin.extra.edit');
//         Route::post('/edit/data/{id}',[ExtraController::class,'EditData'])->name('admin.extra.edit.data');
//         Route::get('/get/amount/{type}',[ExtraController::class,'GetAmount'])->name('admin.extra.get.amount');
//     });
// });
